### ISSUE TITLE
[Package Requset] FTE Quake

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#150]
FTE QuakeWorld is a QuakeWorld derivative which mainly focuses on modding and additional features for both users and servers. Supports NetQuake gamecode and protocol, Hexen 2/Quake 2/Quake 3 maps and models, many QuakeC builtin extensions, and more.

**TODO:**

- [x] Investigate
- [x] Patch files 
 - [x] Makefile
 - [x] common.c (patched now upstream @r5010)
- [x] build dependencies
- [x] Construct debian files
- [x] Check into Vulkan API support
- [x] build package
- [x] testing
- [x] deployment to brewmaster_testing
- [x] Gather feedback
- [x] deployment to brewmaster 
- [x] check into cases where video settings are not being loaded correctly after restart

* [Upstream ticket 1 (fixed)](https://sourceforge.net/p/fteqw/tickets/29/)
* [Makefile](https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/Makefile#l321)

**Comment by ProfessorKaos64** [comment]
@jite , I only saw a Vulkan plugin at http://triptohell.info/moodles/linux_amd64/ when searching. Do you have any references/notes on how to implement this? I just got done making a test package for this.

**Comment by jite** [comment]
Take a look at this: https://qexpo2016.com/afterquake-updated/

**Comment by ProfessorKaos64** [comment]
I did include libvulkan-dev in debian/control. Seems using this is just a matter of including a flag a run-time. I'll have to look more at this when I have some more time. Have to checkout the Makefile again or other areas in the code to see what  dependency files they expect for vulkan.

**Comment by ProfessorKaos64** [comment]
Closed. However, there is a small nag of the video options not saving, looking into that.

**Comment by ProfessorKaos64** [comment]
Video setting issue should be fixed in r5016.
